### ISSUE TITLE
Small issue with kidsathlon leaderboard

### ISSUE THREAD

**Issue by LhasaCM** [freezingsaddles/freezing-web#102]
I noticed the new leaderboard (thank you very much @jrenaut !) - but noticed that some people who should have a score are showing as zero.  Poking around the freezing-web/freezing/web/views/pointless.py file, I _think_ I figured out the issue: the condition is excluding someone whose kidical and/or withkid miles are only derived on rides using both hashtags.  (Example: Peter D, or Barb S).

(Since my Python knowledge is limited to what I just Googled or am guessing from looking at this code, I thought it safest to just mention the issue here than actually fork and edit the file directly.)

The current conditional calculation for the score (in row 179 of the .py file) is:

 `x['kidical'] + x['withkid'] + x['miles_both'] if (x['withkid']>0 and x['kidical']>0) else 0`

...where the "kidical" miles exclude any rides with both tags.  Thus, Barb's score evaluates to 0 because she has no such rides; her kidical miles were part of the same ride as withkid.

I think it will give the desired output if that row is instead changed to:

`x['kidical'] + x['withkid'] + x['miles_both'] if (x['miles_both']>0 or x['withkid'] * x['kidical'] >0) else 0`

By definition - if you have a non-zero "miles_both" then you qualify.  If not, then you need to have both withkid and kidical mileages greater than zero, which is easily confirmed if the product is non-zero (since if either value is zero the product is zero).

**Comment by jrenaut** [comment]
I saw this issue when it went into production. I have a fix that's waiting to get sent to production.

**Comment by LhasaCM** [comment]
Got it.  Thanks again!

**Comment by obscurerichard** [comment]
Looks like the recent deployments fixed this:

![image](https://user-images.githubusercontent.com/341082/51159653-52643b80-1858-11e9-93f8-80b0bc6b7004.png)
