### ISSUE TITLE
Sleaze to the Max leaderboard 

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#117]
I have a couple new BAFS stat suggestions.

I have 7 sleaze ride days for BAFS 2019 but about half of them were sleaze rides to reach my maximum team points for the week (Sleazes to the Max). 

Additionally, 2 of my 7 sleaze rides were a Double Sleaze to the Max: I finished the week with 2 consecutive sleaze ride days to reach my maximum team points for the week.

If the technology allows it my suggestion is to add “Sleazes to the Max” and “Double Sleazes to the Max” as columns to the Individual Sleaze Rides page.

Jim B

**Comment by merlinorg** [comment]
OBE
