### ISSUE TITLE
Add leaderboard for Loopy for Arlington prize

### ISSUE THREAD

**Issue by jrenaut** [freezingsaddles/freezing-web#119]
We need a leaderboard for the _Loopy for Arlington_ prize, given in the past by 
**Current candidate for corrected SQL query given [updated info:**
```select a.name, re.segment_id, count(re.segment_id) as ridden from ride_efforts re, rides r, athletes a where r.id=re.ride_id and r.athlete_id = a.id and re.segment_id in (13943476,13986769,14143039,14149112,13943521,13943546,13943556,13943727,13943600,13943716,13943733, 13943744,13943752,13943762,13943768,13943773) group by athlete_id, segment_id order by name, segment_id```

**Original sql query:**
`select a.name, re.segment_id, count(re.segment_id) as ridden 
from ride_efforts re, rides r, athletes a where r.id=re.ride_id
and r.athlete_id = a.id and
re.segment_id in (13943476,13986769,14143039,13943515,13943521,13943546,13943556,13943727,13943600,13943716,13943733, 13943744,13943752,13943762,13943768,13943773) 
group by athlete_id, segment_id order by name, segment_id`

**Here's the logic that bentbike uses, should be able to do this a lot more efficiently:**
Below is the logic/code I use to calculate the winners in a statistics package called SPSS.

This part sets up variables to count the number of times each segment was ridden and fills in zeros for segments not ridden.

```
COMPUTE ArLoopCCW1 = 0.
COMPUTE ArLoopCCW2 = 0.
COMPUTE ArLoopCCW3 = 0.
COMPUTE ArLoopCCW4 = 0.
COMPUTE ArLoopCCW5 = 0.
COMPUTE ArLoopCCW6 = 0.
COMPUTE ArLoopCCW7 = 0.
COMPUTE ArLoopCCW8 = 0.
COMPUTE ArLoopCW1 = 0.
COMPUTE ArLoopCW2 = 0.
COMPUTE ArLoopCW3 = 0.
COMPUTE ArLoopCW4 = 0.
COMPUTE ArLoopCW5 = 0.
COMPUTE ArLoopCW6 = 0.
COMPUTE ArLoopCW7 = 0.
COMPUTE ArLoopCW8 = 0.
EXECUTE.
```
```
IF (segment_id = 13943476) ArLoopCCW1 = ridden.
IF (segment_id = 13986769) ArLoopCCW2 = ridden.
IF (segment_id = 14143039) ArLoopCCW3 = ridden.
IF (segment_id = 14149112) ArLoopCCW4 = ridden.
IF (segment_id = 13943521) ArLoopCCW5 = ridden.
IF (segment_id = 13943546) ArLoopCCW6 = ridden.
IF (segment_id = 13943556) ArLoopCCW7 = ridden.
IF (segment_id = 13943727) ArLoopCCW8 = ridden.
IF (segment_id = 13943600) ArLoopCW1 = ridden.
IF (segment_id = 13943716) ArLoopCW2 = ridden.
IF (segment_id = 13943733) ArLoopCW3 = ridden.
IF (segment_id = 13943744) ArLoopCW4 = ridden.
IF (segment_id = 13943752) ArLoopCW5 = ridden.
IF (segment_id = 13943762) ArLoopCW6 = ridden.
IF (segment_id = 13943768) ArLoopCW7 = ridden.
IF (segment_id = 13943773) ArLoopCW8 = ridden.
EXECUTE.
```
This step creates a new file with a single line for each rider and the counts of all the segments ridden.
```
AGGREGATE 
/OUTFILE='e:\Data\Loop_counts_2019.sav' 
/BREAK=Name 
/ArLoopCCW1=SUM(ArLoopCCW1) 
/ArLoopCCW2=SUM(ArLoopCCW2) 
/ArLoopCCW3=SUM(ArLoopCCW3) 
/ArLoopCCW4=SUM(ArLoopCCW4) 
/ArLoopCCW5=SUM(ArLoopCCW5) 
/ArLoopCCW6=SUM(ArLoopCCW6) 
/ArLoopCCW7=SUM(ArLoopCCW7) 
/ArLoopCCW8=SUM(ArLoopCCW8) 
/ArLoopCW1=SUM(ArLoopCW1) 
/ArLoopCW2=SUM(ArLoopCW2) 
/ArLoopCW3=SUM(ArLoopCW3) 
/ArLoopCW4=SUM(ArLoopCW4) 
/ArLoopCW5=SUM(ArLoopCW5) 
/ArLoopCW6=SUM(ArLoopCW6) 
/ArLoopCW7=SUM(ArLoopCW7) 
/ArLoopCW8=SUM(ArLoopCW8). 
GET 
FILE='e:\Data\Loop_counts_2019.sav'. 
DATASET NAME DataSet2 WINDOW=FRONT. 
SAVE OUTFILE='e:\Data\Loop_counts_2019.sav' 
/COMPRESSED.
```
These steps count the number of completed loops as the number of times the least-ridden segment was ridden. Note that in 2019, I excluded from these counts the segments in the Rosslyn area (ArLoopCW2, ArLoopCW3, ArLoopCCW6, and ArLoopCCW7) due to the construction and the poor condition of the north end of the MVT from the water seepage and resulting ice.
```
COMPUTE C_Loop_count = MIN(ArLoopCW1,ArLoopCW4,ArLoopCW5,ArLoopCW6,ArLoop CW7,ArLoopCW8).
COMPUTE CC_Loop_count = MIN(ArLoopCCW1,ArLoopCCW2,ArLoopCCW3,ArLoopCCW4,Ar LoopCCW5,ArLoopCCW8).
EXECUTE.
COMPUTE Total_Loop_Count = C_Loop_count + CC_Loop_count.
COMPUTE Balanced_Loop_Count = min(C_Loop_count,CC_Loop_count).
EXECUTE.
SAVE OUTFILE='e:\Data\Loop_counts_2019.sav' 
/COMPRESSED.
```
It's pretty brute force because I'm not much of a programmer. I'm not sure how adaptable this will be for creating a leaderboard. Let me know if you have any questions.

**Comment by obscurerichard** [comment]
The original requestor gave these segment names and numbers:

| Segment Name | Segment Number | 
| ------------- | ------------- |
| ArLoopCCW1 |	13943476 |
| ArLoopCCW2 |	13986769 |
| ArLoopCCW3 |	14143039 |
| ArLoopCCW4 |	14149112 |
| ArLoopCCW5 |	13943521 |
| ArLoopCCW6 |	13943546 |
| ArLoopCCW7 |	13943556 |
| ArLoopCCW8 |	13943727 |
| ArLoopCW1 |	13943600 |
| ArLoopCW2 |	13943716 |
| ArLoopCW3 |	13943733 |
| ArLoopCW4 |	13943744 |
| ArLoopCW5 |	13943752 |
| ArLoopCW6 |	13943762 |
| ArLoopCW7 |	13943768 |
| ArLoopCW8 |	13943773 |

**Comment by bentbike33** [comment]
I've changed a couple of the segments to work better for people going to HDCC.

Segment Name	Segment Number
ArLoopCCW1	        13943476
ArLoopCCW2	22382559
ArLoopCCW3	14143039
ArLoopCCW4	14149112
ArLoopCCW5	13943521
ArLoopCCW6	13943546
ArLoopCCW7	        13943556
ArLoopCCW8	13943727
ArLoopCW1	13943600
ArLoopCW2	13943716
ArLoopCW3	13943733
ArLoopCW4	13943744
ArLoopCW5	13943752
ArLoopCW6	13943762
ArLoopCW7	22382566
ArLoopCW8	13943773

Thanks.

**Comment by bentbike33** [comment]
More segment changes because of construction detours.

Segment Name	Segment Number
ArLoopCCW1	13943476
ArLoopCCW2	22382559
ArLoopCCW3	14143039
ArLoopCCW4	14149112
ArLoopCCW5	13943521
ArLoopCCW6	13943546
ArLoopCCW7	13943556
ArLoopCCW8	22395389
ArLoopCW1	22395425
ArLoopCW2	13943716
ArLoopCW3	13943733
ArLoopCW4	13943744
ArLoopCW5	13943752
ArLoopCW6	13943762
ArLoopCW7	22382566
ArLoopCW8	13943773
