### ISSUE TITLE
Update scoring system for 2020 - implement decreasing points per mile

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#123]
Ten points are given for every day someone rides at least a mile, and additional points as follows: 10 points for mile 1, 9 points for mile 2, 8 points for mile 3, etc.  Miles 10 and over each day earn one point each.

**Comment by spfrantz** [comment]
Is it correct to say that this requires (only) modifying the `daily scores` view in [freezing-model/freezing/model/__init__.py](https://github.com/freezingsaddles/freezing-model/blob/f21a7b2eb13441f0d2305f79b710e1df3ee16d2d/freezing/model/__init__.py) ?

**Comment by obscurerichard** [comment]
@spfrantz yes, I think you have it. All we have to do is modify that view and the rest of the SQL queries in the `freezingsaddles/freezing-web` project will use the view.

**Comment by obscurerichard** [comment]
We will have to adjust [some of the queries in freezing-web](https://github.com/freezingsaddles/freezing-web/blob/master/freezing/web/views/shared_sql.py) also because they have assumptions about how many points make a sleaze ride that the new scoring system invalidates.

The new scoring system is essentially a step function, and we should make sure that fractional miles are multiplied by the right multiplier. A [SQL CASE statement](https://dev.mysql.com/doc/refman/5.7/en/case.html) could do the trick nicely.

**Comment by spfrantz** [comment]
SteveO's [suggestion](http://bikearlingtonforum.com/showthread.php?15056-BAFS-2020-teams-and-rules-discussion&p=193824#post193824) was to implement the fractional miles as a smooth curve rather than a step function. If we do this, the formula for rides between 1 and 10 miles is simply `10 + 0.5 * (21n - n^2)`. 

Is this a fair implementation or do we really want a step function?

**Comment by obscurerichard** [comment]
It's a fair implementation, let's do it.

**Comment by obscurerichard** [comment]
```$ python
Python 2.7.16 (default, Sep  2 2019, 12:00:52)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> [10 + 0.5 * (21 * n - n * n) for n in [m / 5.0 for m in range(5,50)]]
KeyboardInterrupt
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
>>> quit()
[rbulling@Codex obscure-scripts (master)]$ python3
Python 3.7.5 (default, Nov  1 2019, 02:16:38)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> [10 + 0.5 * (21 * n - n * n) for n in range(1,10)]
[20.0, 29.0, 37.0, 44.0, 50.0, 55.0, 59.0, 62.0, 64.0]
>>> [10 + 0.5 * (21 * n - n * n) for n in [m / 5.0 for m in range(5,50)]]
[20.0, 21.88, 23.72, 25.52, 27.28, 29.0, 30.68, 32.32, 33.92, 35.480000000000004, 37.0, 38.480000000000004, 39.919999999999995, 41.32000000000001, 42.68, 44.0, 45.28, 46.52, 47.72, 48.879999999999995, 50.0, 51.08, 52.120000000000005, 53.12, 54.08, 55.0, 55.88000000000001, 56.72, 57.519999999999996, 58.279999999999994, 59.0, 59.68000000000001, 60.32, 60.92, 61.47999999999999, 62.0, 62.48, 62.92, 63.32, 63.68, 64.0, 64.28, 64.52, 64.72, 64.88]```

**Comment by obscurerichard** [comment]
#130 addresses this

**Comment by obscurerichard** [comment]
Thank you @spfrantz !  :shipit:
