### ISSUE TITLE
Add attributions for photos in gallery

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#145]
Steve O [wrote](http://bikearlingtonforum.com/showthread.php?15362-Freezing-Saddles-Technology-2020-Thread&p=195632#post195632):

> One of my favorite things to do is look at the photos on the home page. Fun!
> 
> In the past I believe the photos included reference to who posted them. This year there is no attribution. Any way we can add that?
> 
> Also, is the web site picking up photos from Instagram? If so, what is the appropriate hashtag?

Strava stopped integrating with Instagram several years ago (see [freezing-sync issue #1](https://github.com/freezingsaddles/freezing-sync/issues/1)), so there's no Instagram integration. It has its own photo service now, so only photos you add to your ride on Strava will show up.

If you click on a photo, it will show a caption.

However, should probably add captions in a way that they are visible on the home page also.

**Comment by joetats** [comment]
Once I get a local version running I'll start looking at some of the backend stuff, but for alas...
