### ISSUE TITLE
Loopy for Arlington Leaderboard Bug

### ISSUE THREAD

**Issue by bentbike33** [freezingsaddles/freezing-web#165]
Competitors are reporting that the leaderboard is not counting their loops even though all 8 segments show up in their rides' segment lists.  I have not experienced this issue personally even when completing a loop in 2 separate rides, so I can offer no help with diagnostics.  [See here for details](http://bikearlingtonforum.com/showthread.php?15537-BAFS-2020-Pointless-Prizes-Loopy-for-Arlington)

**Comment by merlinorg** [comment]
Looking at data I think there's an issue with syncing efforts from Strava, sometimes they don't appear to be there when we ask. Plausibly can be resynced.

**Comment by merlinorg** [comment]
https://github.com/freezingsaddles/freezing-sync/issues/18

**Comment by obscurerichard** [comment]
CBGanimal wrote:


    Yes! My number is correct! THANK YOU!


    Sent from my iPad using Tapatalk

**Comment by obscurerichard** [comment]
@bentbike33 can you double-check your numbers too?

**Comment by obscurerichard** [comment]
I think we have this licked but there may be some more segment fetching refinement we need to do to _catch them all_, Pokemon style.

**Comment by bentbike33** [comment]
My numbers were always right, which made it hard to provide input for
diagnostics. Thanks for getting it working!

**Comment by obscurerichard** [comment]
I am pretty sure after recent fixes that we really have this fixed.
