### ISSUE TITLE
Bridge Crossing Pointless Leaderboard

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#174]
Stephen Dorey wrote:

> Hi obscurerichard,
> 
> I have a question about how pointless prizes are monitored and awarded. I contacted cvcalhoun who asked me to send a message to you since my idea would require a leaderboard using strava data.
> 
> My idea is to award a pointless prize based on riders crossing specific bridges that are slightly out of town. With more points for the more remote bridges. I.e. riders have to get out somewhere cold and possibly windy. The idea would be something like 1 point for crossing a bridge on the Anacostia (I've not decided which yet) 2 points for the chain bridge, 3 points for the Woodrow Wilson bridge and 10 points for a crossing at Whites Ferry (assuming there's a suitable segment). Riders could get points for crossing in either direction.
> 
> Do you think this would be possible and not take too much admin once set up?

The short answer is that it would definitely be possible to do this, we have other leaderboards that do similar segment-based things. This might require a bit more work than the average one.

It is also helpful to have specific Strava segment IDs already researched to make it easier to create these leaderboards.

**Comment by bhavika** [comment]
@obscurerichard what type of help do you need here? 

I'd be happy to look up the Strava segment IDs to start.

**Comment by bhavika** [comment]
Anacostia:
 - S Capitol Bridge (North): https://www.strava.com/segments/1185871
 - Frederick Douglas Bridge / S Capitol (South): https://www.strava.com/segments/1522932
 - Sousa Bridge SE - https://www.strava.com/segments/9571955
 
Woodrow Wilson Bridge 
 - westbound: https://www.strava.com/segments/16500889 
 - eastbound: https://www.strava.com/segments/24428918

White's Ferry (Eastbound): https://www.strava.com/segments/6964237

**Comment by bhavika** [comment]
Oh yikes I just noticed this ticket is from last year 😅 well!

**Comment by obscurerichard** [comment]
@bhavika thanks for trying to help - this is a community effort. Alas, while this is a super cool idea I don't think Stephen Dorey is still playing the game. I'm closing this for now, but we have these segments for posterity if we revive it or do something similar.
