### ISSUE TITLE
TimV's missing Haines Point laps

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#175]
TimV is offline Very Junior Member

Join Date
    Jan 2014
Location
    Arlington, VA

    Hi Richard -

    I saw Chris Watson at the HH last night and asked her who can help with HP laps and she pointed me to you.

    I hate to be a nudge, I did 4 laps at HP on Sunday but they didn't show up in https://freezingsaddles.org/alt_scoring/indiv_hains

    I did 3 laps earlier in the month and they did show up in the tally.

    Again, sorry to bug you with this. Thanks for your help!

    Tim

**Comment by merlinorg** [comment]
I think I'm working on this. Multiple Strava sync issues.

**Comment by obscurerichard** [comment]
I think this is resolved @merlinorg  - I am checking with TimV about it on the forum now.

**Comment by obscurerichard** [comment]
I asked TimV on the forum about it and he says:

> Yep, looks good! Thanks!
