### ISSUE TITLE
Update pointless prize leaderboards for 2021 hashtags

### ISSUE THREAD

**Issue by spfrantz** [freezingsaddles/freezing-web#207]
Leaderboards have not been updated for this year's pointless prize hashtags. A list of currently-sponsored prizes with hashtags is posted at:

http://bikearlingtonforum.com/showthread.php?18042-Pointless-Prize-Thread-2021

**Comment by jrenaut** [comment]
We need a process for people making official requests. Does every hashtag contest need a leaderboard? Should the leaderboard show number of rides or mileage? Both? Some custom thing?

Any brilliant ideas on how to collect leaderboard requests?

**Comment by merlinorg** [comment]
We could let people create them in the app with their instructions and a choice of rides or miles, stored in the database, creator is sponsor. Would somewhat eliminate annual maintenance.

**Comment by obscurerichard** [comment]
Creating them in the app is going to be quite a lift.

What I've done in the past when I've been on top of it is to look at the pointless prize thread and create separate GitHub issues for each new leaderboard, and try to guide people away from doing hashtags with embedded years in them like #fs2021foobar.

**Comment by obscurerichard** [comment]
I also like to go easy on removing pointless prize links, because people may decide to sponsor them for the current year.

**Comment by obscurerichard** [comment]
This got resolved in 2021 and I also brought back more of the ones I love in #210 and #215
