### ISSUE TITLE
Some team & athlete names/labels are missing in the leaderboard charts

### ISSUE THREAD

**Issue by spfrantz** [freezingsaddles/freezing-web#209]
In the chart versions of the [team](https://freezingsaddles.org/leaderboard/team) and [individual](https://freezingsaddles.org/leaderboard/individual) leaderboards, some bars are missing the team/athlete name label. This appears to be the case only for longer names, such as that of our beloved website administrator.

In solving this, it would be ideal to avoid truncating longer names.

**Comment by obscurerichard** [comment]
#252 solved this, alas, with truncating names.
