### ISSUE TITLE
Restore some deleted leaderboards from previous years

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#210]
I think that #208 went too far in removing leaderboards that people were actively using and were fun, such as the Adulting leaderboard that should be merged with Errandeuring and the POGGIO leaderboards. But I did not have time to fix it in a timely way so I'm going to release #208 and leave this as placeholder to come back to.

![image](https://user-images.githubusercontent.com/341082/108007360-d22ada00-6fcb-11eb-8f81-ea1bcef7db2e.png)

**Comment by obscurerichard** [comment]
cc: @spfrantz

**Comment by spfrantz** [comment]
I'd be glad to restore Poggio and any others that we think people were tracking. The finer points of adulting vs errandeering and whether they can be merged elude me. We could solicit feedback on this if we're unsure.

There was some confusion in the coffee group this year about which hashtag they're using -- I will redo that as a `/generic` board that recognizes both hashtags.

I'll keep an eye on the forum to see if there's any response to the board updates.

**Comment by obscurerichard** [comment]
Here's an adulting generic leaderboard diff that would encompass both:

```
diff --git a/leaderboards/adulting.yml b/leaderboards/adulting.yml
index 6230a0e..a91808c 100644
--- a/leaderboards/adulting.yml
+++ b/leaderboards/adulting.yml
@@ -1,7 +1,7 @@
 ---
 title: Adulting
-description: "Pointless prize for doing stuff on your bike you might be tempted to do in your car. Groery store, post office, pharmacy dentist, manicurist, gym, farmers market, dry cleaning, bike shop, library, etc. Commutes, coffee rides, kid pick up / drop off do not count. Tag rides with #adulting."
-url: http://bikearlingtonforum.com/showthread.php?15602-Pointless-Prize-Adulting-(aka-errandaneuring-if-you-so-fancy)-FS2020Adulting
+description: "Pointless prize for doing stuff on your bike you might be tempted to do in your car. Grocery store, post office, pharmacy dentist, manicurist, gym, farmers market, dry cleaning, bike shop, library, etc. Commutes, coffee rides, kid pick up / drop off do not count. Tag rides with #adulting or #freezingerrands2021."
+url: http://bikearlingtonforum.com/showthread.php?18042-Pointless-Prize-Thread-2021/page7
 fields:
   - name: id
     visible: false
@@ -9,11 +9,11 @@ fields:
     label: Athlete
     format: "<a href=\"/people/{id}\">{athlete_name}</a>"
   - name: adulting_rides
-    label: Adulting Rides
+    label: Errandeering Rides
     rank_by: true
 query: |
   select A.id, A.display_name as athlete_name, count(R.id) as adulting_rides
   from lbd_athletes A join rides R on R.athlete_id = A.id
-  where R.name like '%#adulting%' collate utf8mb4_general_ci
+  where R.name like '%#adulting%' or R.name like '%#freezingerrands%' collate utf8mb4_general_ci
   group by A.id, A.display_name
   order by adulting_rides desc
```

**Comment by obscurerichard** [comment]
I saw that you deleted the code for some of the leaderboards, which is generally fine (see [The Codeless Code #41 - Garbage](http://thecodelesscode.com/case/41) but a part of me just wants to disable the menu items for bits we are not using instead of removing the code for unsponsored leaderboards entirely, because it would make it easier to reactivate them in future years and more obvious for the programmers.
