### ISSUE TITLE
Add (back) support for syncing Instagram photos

### ISSUE THREAD

**Issue by hozn** [freezingsaddles/freezing-web#22]
Sync has broken for instagram photos.  I believe this was due to a change in Strrava API and hence changes in Stravalib, but I have not investigated this deeply.

**Comment by schvin** [comment]
I will tinker with this.

**Comment by hozn** [comment]
Ok, great -- let us know what you find.  Also, contact me to get setup with access to the server so you can use existing API keys.

**Comment by hozn** [comment]
I think the more correct issue here is now https://github.com/freezingsaddles/freezing-sync/issues/1

I don't know that we care about Instagram photos; they're not so easy to sync.  But we can easily get the non-primary native photos.
