### ISSUE TITLE
Change architecture to use webhooks

### ISSUE THREAD

**Issue by hozn** [freezingsaddles/freezing-web#24]
This would be a big change, but webhooks should make it possible to have more timely update of rides and less wasted resources polling Strava.

http://strava.github.io/api/partner/v3/events/

**Comment by hozn** [comment]
Note that the Freezing Saddles application is now able to use the new beta webhooks which include hooks for update, etc.

Snippet from the email:
```

The Strava API Team will release an upgraded activity-update webhook events system to all apps with a webhook events subscription on January 15, 2018; all existing subscriptions will be converted to the new system on that date. The new system will enable apps to receive webhook events when an activity has been created, deleted, or updated:

Activity title change
Activity type change
Photos added/removed
Activity privacy change, only for apps with a `view_private` access token

```

**Comment by hozn** [comment]
This is becoming a higher priority.  Our API calls are regularly exceeding rate limit now.

**Comment by hozn** [comment]
Ok, strava rate limiting is becoming a usability issue now with people unable to authorize the app or perform logins.

**Comment by jrenaut** [comment]
Can we break this up into more manageable chunks? Beginning of the year is really busy for me at work, then we're going to Australia in the middle of February, so I struggle to find time for a big undertaking. But if we can break it into smaller pieces that can be tackled in a few hours, i can probably help with this

**Comment by hozn** [comment]
Yeah, I've started to do that, though I'm still in the R&D phase to figure out what it looks like to use webhooks.  I'll write up a plan, though, when I know more.

**Comment by obscurerichard** [comment]
I'm pretty sure this got resolved before the 2019 Freezing Saddles competition began, this is what the `freezing-sync` project does now, right @hozn ? I think we can close this.

**Comment by obscurerichard** [comment]
It's what `freezing-nq` does, see https://github.com/freezingsaddles/freezing-nq. Closing!
