### ISSUE TITLE
Hours look totally sus

### ISSUE THREAD

**Issue by merlinorg** [freezingsaddles/freezing-web#240]
Average 1185mh-1. Only 6 hours below zero?

> 0 teams. 283 contestants.
> 845 rides. 9 hours. 10,670 miles ridden.
> 6 hours below freezing. 0 hours in the rain. 0 hours in the snow.

**Comment by obscurerichard** [comment]
Yeah, this does look suspicious. Also, 0 hours in the rain or snow? We've had plenty of rain in the last week and by today it should have registered.

I suspect an issue with https://github.com/freezingsaddles/freezing-sync though and the new weather handling code.

**Comment by merlinorg** [comment]
The database is 100%, it's the python upgrade and the bizarre thing that we're doing to divide N by 3600. We should just divide N by 3600 which I will do.
