### ISSUE TITLE
Strava Developer Program may need a new registration

### ISSUE THREAD

**Issue by obscurerichard** [freezingsaddles/freezing-web#254]
I got an email from the Strava Developer program that indicated that all apps are going to need a round of reviews to stay active. It pointed to this announcement: https://communityhub.strava.com/t5/strava-insider-journal/introducing-strava-s-updated-developer-program/ba-p/9061

We are still using the original Strava app registration that @hozn created I think. I'm not sure if Hans has done this anything about this. 

There's a [registration form](https://share.hsforms.com/1VXSwPUYqSH6IxK0y51FjHwcnkd8?utm_medium=email&_hsmi=273513128&utm_content=273513128&utm_source=hs_email) we may need to submit.

Alas we are already past the March 4, 2024 deadline.

**Comment by hozn** [comment]
Oof -- I did not realize that this hadn't been moved, so I was not paying attention when Strava emailed me saying that apps needed to be re-registered.  😢   -- Probably this should not be associated w/ my Strava account, but let me know if someone wants me to reach out to Strava, etc.

**Comment by obscurerichard** [comment]
I submitted the form as instructed today. I hope they get back to us soon. If I don't hear from them by this Friday, I'll write them an email asking them to expedite the review. cc @hozn

**Comment by obscurerichard** [comment]
We got approved today!

> From: Strava API Team <developers@strava.com>
> Subject: Your submission was approved!
>
> **Your submission was approved!**
>
> Congratulations, and welcome to Strava’s Developer Program. We're excited to have you on board! 
>
> Moving forward, here’s what you can expect for your apps:
>
> * Overall Rate Limit: allows for 3,300 requests every 15 min, with up to 165,000 requests per day
> * Read Rate Limit: allows for 600 requests every 15 min, with up to 30,000 requests per day
> * Athlete Capacity: 9,999
>
> And if you ever need to reach out, here’s how: 
> 
>    Community Support: [our new developer community](https://d2v-2r04.na1.hubspotlinks.com/Ctc/W+113/d2v-2R04/VWxGVt1x6RtNW7wL0vl7HVjjPVLsY3L5nK7S2N6G5Tsg3m2ndW95jsWP6lZ3p8W5RYprz7sstdNW860PtM3bg0yhW80y1sZ2TdsmrW56Dzc65yBBC4W74hX9s3KnMkCW79N36r5bNQjJVjZjKL9dlBylW85p61_6V16PqW12xRtZ3qg_PxV4HpRV4q_cmjW2r-xYh34tdYZW3_5XW52PKZfRW5q5mY_9crWyHW3R3rRN1-SWFfW2cRpFc4L667WW8VL9mN76t4SHW7KSBpZ79sc-4W8hNxqg3JqggxVg-_5v1ymF67W4QlrjC3fVNXcW3fpH_c5KlfY3VFW7HD7TrkSPW3rFlGl5n_hHJVh5z7_2bdqdWVBVBNh2nKL0qN3W-D5n52-cgW4szV_Q4bPzr3W2mMlbp7BDgRjW8RPJn87VykmzW55nb-p1nYDzmf49BJ2M04)
