### ISSUE TITLE
Geojson APIs suspeculatively not scalable

### ISSUE THREAD

**Issue by merlinorg** [freezingsaddles/freezing-web#310]
Use of the full API without some caching in place and, probably, some time bounds on the rides, will likely lead to catastrophe.

**Comment by obscurerichard** [comment]
Confirmed.

I fixed the GeoAlchemy2 underlying code that produces these and tested locally on the 2024 season data.

Without any limits, it was taking 1m41.040s to get the full set.

The default you picked for the newer map functions of limiting results to 1024 is sensible. Having a max of 2048 is a reasonable denial of service prevention measure, so I've put that in as part of #331
