### ISSUE TITLE
Resolve the tabtastrophe

### ISSUE THREAD

**Issue by merlinorg** [freezingsaddles/freezing-web#325]
HTML files are a blend of tabs and spaces! 😱 Is there a black for that?

**Comment by obscurerichard** [comment]
I know. It's awful! There's HTML Tidy. I really gave Tidy a workout today and even have a shell script wrapper [btidy.sh](https://github.com/obscureorganization/obscure-scripts/blob/main/btidy.sh) that is _designed_ to pull in just HTML body fragments and work as a filter.

But it _also_ may not play well with jinja2 templates. I may do a little testing now but I'm not optimistic.

See here for some potential candidates:

https://github.com/mfussenegger/nvim-lint/issues/236

the obvious and most promising may be https://djlint.com/

**Comment by merlinorg** [comment]
@obscurerichard I thoroughly approve of `djlint --reformat freezing/web/`. Don't try its CSS/JS options, there lies hate.
