### ISSUE TITLE
Differences (rounding?) between a user's points on individual leaderboard (text vs chart)

### ISSUE THREAD

**Issue by jocar** [freezingsaddles/freezing-web#33]
Right now for the top 3, I'm seeing this:
```
User|Points (Text)|Points (Chart)
--------------------------------
Josh A|111|110
David H|92|91
Bob J|91|91
```
The point value from the text version is from the hover/tool-tip. Sometimes they're equal, sometimes they're not. Haven't checked to see if there's any users with an absolute value of the difference greater than 1.

**Comment by hozn** [comment]
Interesting.  Yeah, we should be implementing the same rounding logic (looks like we're not)!

**Comment by obscurerichard** [comment]
I think we might need to validate that this is still a problem, and then decide whether to fix it.
