### ISSUE TITLE
Build new API-only application for receiving and enqueuing webhook "events" 

### ISSUE THREAD

**Issue by hozn** [freezingsaddles/freezing-web#40]
I'm thinking this will all run in Docker containers.

1. [Falcon](https://falconframework.org/)
2. [envparse](https://github.com/rconradharris/envparse)
3. [beanstalkd](https://github.com/kr/beanstalkd)

**Comment by obscurerichard** [comment]
I'm pretty sure this got resolved before the 2019 Freezing Saddles competition began, this is what the `freezing-sync` project does now, right @hozn ?

**Comment by obscurerichard** [comment]
The way this ended up working:

1. Strava has a webhook registered that pushes events to http://hook.freezingsaddles.org/.
2. The producton `docker-compose` setup maps that from NGINX to a listener [`freezing-nq`](https://github.com/freezingsaddles/freezing-nq) that parses the incoming messages and pushes them into `beanstalkd`. This is a very fast operation, and it's a good idea to decouple the listener from the processor that does heavy lifting. 
3. The `freezing-sync` container polls `beanstalkd` for mesages and processes them, inserting records into the MySQL database 

Once the records are in the database the `freezing-web` container does queries that aggregate the data on each request for the leaderboards.
