### ISSUE TITLE
Create individual points per mile scoreboard

### ISSUE THREAD

**Issue by jrenaut** [freezingsaddles/freezing-web#44]
Most of this code is written, just needs to be tweaked. We have [points per mile by TEAM](https://github.com/freezingsaddles/freezing-web/blob/0fd1f860d97c07b48c38b222b5090d4a8b64c683/bafs/views/pointless.py#L30), so you just need to create a new view function and corresponding template (copy and tweak [billygoat.html](https://github.com/freezingsaddles/freezing-web/blob/master/bafs/templates/pointless/billygoat.html)).

**Comment by hozn** [comment]
We should also view this as candidate for refactoring per #42
