### ISSUE TITLE
Team cumulative leaderboard shouldn't show Friends of BAFS

### ISSUE THREAD

**Issue by jrenaut** [freezingsaddles/freezing-web#46]
The team cumulative leaderboard doesn't take the leaderboard_exclude flag into account, so the Friends of BAFS are considered a team and are showing up. 

[Link to relevant query](https://github.com/freezingsaddles/freezing-web/blob/d2c0a445e189e0a359fa134258e0d5e14bd9de56/freezing/web/views/chartdata.py#L586)

**Comment by merlinorg** [comment]
Fixed in the dim and distant past.
