### ISSUE TITLE
Leaderboard for #donut

### ISSUE THREAD

**Issue by FS18Edelweiss** [freezingsaddles/freezing-web#50]
Hi, I would like a table to see how many rides, and riders, claimed Doughnut Rides.
Thanks, Kate

**Comment by hozn** [comment]
Ok, no problem. Thanks for creating this ticket!

**Comment by obscurerichard** [comment]
Adding a generic leaderboard similar to the dumpling ride one would fullfill this. See #85 for a PR that does similar things.

**Comment by FS18Edelweiss** [comment]
Hi,

   I am not planning to sponsor the Doughnut rides this year.  I live in Colorado and it's too hard, and too depressing, to coordinate from afar, and witness everyone enjoying those amazing doughnuts.  I live in  a doughnut desert.
I asked some of my dedicated doughneuers to take over, but so far have not found a taker. Maybe you can ask the crowd at the Happy Hour?

Thanks, Kate


Sent from my Galaxy Tab® S2


-------- Original message --------

**Comment by obscurerichard** [comment]
Yes, that's an excellent idea! I will ask at the happy hour. Thanks Kate!
