### ISSUE TITLE
Names on FS leaderboard may be first name only, whereas people are expecting a last initial

### ISSUE THREAD

**Issue by chuxtr** [freezingsaddles/freezing-web#80]
Richard - I don't know how many people this affects, but my name changed on the leaderboard. It was Chuck P. Now it's just Chuck. I assume it pulls the name from Strava? It seems like it would be a good idea to have the first letter of whatever last name people are using. Especially if there's more than one person with the same first name. Thanks and cheers, Chuck

**Comment by obscurerichard** [comment]
Yeah, it pulls the name from Strava.

The site tries to use just a first name if it is unambiguous, and then starts assigning first name plus at least the first initial. You're not the only one who was affected. I think I'm going to change it to always include a last initial if one is present as the default.

**Comment by obscurerichard** [comment]
This got resolved last year.
