### ISSUE TITLE
Leaderboard for Kidsathlon pointless prize

### ISSUE THREAD

**Issue by LhasaCM** [freezingsaddles/freezing-web#87]
**Note: This is something I can easily do in Excel again this year, but thought I may as well go ahead and document the issue/request in case someone is interested in working on it - or in case I ever get a chance to teach myself the languages to be useful.  Definitely low priority, limited audience, and non-trivial difficulty, relatively speaking**

In addition to the direct hashtag-based leaderboards, there's also a "combined" prize I offer that is based on how one fares in both categories.  This is calculated in Excel and manually pasted to the forum, though theoretically there _could_ be a leaderboard.  This is only mentioned briefly in this year's thread (http://bikearlingtonforum.com/showthread.php?14004-FS-2019-Kid-Related-Pointless-Prizes) and spelled out in more detail in last year's, so it wouldn't immediately pop up in reading the forum.

The combined prize currently is determined by taking the "geometric mean" of the mileage share for each of the #kidical and #withkid leaderboards, respectively.  (Computationally, since the order is important whereas the value itself is a meaningless number,, I actually calculate the product of the two shares to avoid taking the square root of zero.)  I've uploaded an Excel file that shows the standings/calculations as of yesterday morning since that's probably easier to understand that writing more words about it.

[kid_leaderboard.xlsx](https://github.com/freezingsaddles/freezing-web/files/2737770/kid_leaderboard.xlsx)

**Comment by obscurerichard** [comment]
Thank you for describing this so thoroughly and for attaching a spreadsheet as an example. I'd be happy to help teach you enough Python for you to be able to code this yourself and help you set up the development environment too.

Or maybe someone on the technology team will decide to pick up this torch...

**Comment by obscurerichard** [comment]
Oh yeah - have a  🌮 for submitting your first GitHub issue @LhasaCM !

🎉

**Comment by jrenaut** [comment]
@LhasaCM see updated excel file - does the ability to count rides tagged with both kidical and withkid change your calculation?
[kid_leaderboard.xlsx](https://github.com/freezingsaddles/freezing-web/files/2752083/kid_leaderboard.xlsx)

**Comment by jrenaut** [comment]
@LhasaCM Either of those is easy to do, just let me know what you prefer
