### ISSUE TITLE
Points per mile leaderboard

### ISSUE THREAD

**Issue by chuxtr** [freezingsaddles/freezing-web#90]
Please note that the minimum number of ride days changed from 36 to 40. Thank you!

**Comment by obscurerichard** [comment]
Why does it change from 36 to 40? I'm changing it now, but I'm curious what this is based on.

**Comment by chuxtr** [comment]
Somewhat arbitrary.  In the past, I think I based it on a minimum of 3 rides per week for the duration of Freezing Saddles.  This year, I  wanted to make it more like riding ~half the days of Freezing Saddles.
Thank you!
    On Thursday, January 10, 2019, 6:39:20 PM EST, Richard Bullington-McGuire <notifications@github.com> wrote:  
 
 
Why does it change from 36 to 40? I'm changing it now, but I'm curious what this is based on.
